import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header'
import Loading from '../components/Loading'
import Page from '../components/Page'

export default function Home() {
  const [users, setUsers] = useState([])
  const [loading, setLoading] = useState(false)
  useEffect(() => {
    const getData = async () => {
      try {
        setLoading(true)
        const res = await axios.get('/users?_sort=createdAt&_order=desc')
        if (res.status == 200 && res.data) {
          setUsers(res.data)
          setLoading(false)
        }
      } catch (err) {
        console.log(err)
      }
    }
    getData()
  }, [])
  if (loading) return <Loading />
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Page users={users} />
      </main>

    </div >
  )
}
